import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter,Sora } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const sora = Sora({subsets:['latin'],weight:[
  '100',
  '200',
  '300',
  '400',
  '500',
  '600',
  '700',
  '800'
]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sora.className}>
      <Header />
        {children}
      </body>
    </html>
  )
}
